[
  {
    "input": {
      "name": "Product1",
      "info": "Desc1",
      "price": "2147483647"
    },
    "status_code": "exception",
    "response": "HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /datatb/product/add/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabe004c6d0>: Failed to establish a new connection: [Errno 61] Connection refused'))",
    "mutation_type": "boundary_value",
    "request_id": 3,
    "timestamp": "2025-04-24T18:38:40.696288",
    "error": "HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /datatb/product/add/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabe004c6d0>: Failed to establish a new connection: [Errno 61] Connection refused'))"
  },
  {
    "input": {
      "name": "Product1",
      "info": "Desc1",
      "price": "nan"
    },
    "status_code": "exception",
    "response": "HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /datatb/product/add/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabe0062400>: Failed to establish a new connection: [Errno 61] Connection refused'))",
    "mutation_type": "boundary_value",
    "request_id": 8,
    "timestamp": "2025-04-24T18:38:40.708797",
    "error": "HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /datatb/product/add/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabe0062400>: Failed to establish a new connection: [Errno 61] Connection refused'))"
  },
  {
    "input": {
      "name": "TestItem",
      "info": "Sample",
      "price": "1e-06"
    },
    "status_code": "exception",
    "response": "HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /datatb/product/add/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac10e2ce20>: Failed to establish a new connection: [Errno 61] Connection refused'))",
    "mutation_type": "boundary_value",
    "request_id": 16,
    "timestamp": "2025-04-24T18:38:40.732666",
    "error": "HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /datatb/product/add/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac10e2ce20>: Failed to establish a new connection: [Errno 61] Connection refused'))"
  },
  {
    "input": {
      "name": "TestItem",
      "info": "Sample",
      "price": "1e-06"
    },
    "status_code": "exception",
    "response": "HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /datatb/product/add/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabe004cb50>: Failed to establish a new connection: [Errno 61] Connection refused'))",
    "mutation_type": "boundary_value",
    "request_id": 18,
    "timestamp": "2025-04-24T18:38:40.737080",
    "error": "HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /datatb/product/add/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabe004cb50>: Failed to establish a new connection: [Errno 61] Connection refused'))"
  },
  {
    "input": {
      "name": "TestItem",
      "info": "Sample",
      "price": "inf"
    },
    "status_code": "exception",
    "response": "Out of range float values are not JSON compliant",
    "mutation_type": "boundary_value",
    "request_id": 20,
    "timestamp": "2025-04-24T18:38:40.740931",
    "error": "Out of range float values are not JSON compliant"
  }
]