[
  {
    "input": {
      "name": "Product1",
      "info": "Desc1",
      "price": "20",
      "divide_by": "0"
    },
    "status_code": "exception",
    "response": "HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /datatb/product/add/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac10e2cd00>: Failed to establish a new connection: [Errno 61] Connection refused'))",
    "mutation_type": "division_by_zero",
    "request_id": 2,
    "timestamp": "2025-04-24T18:38:40.692636",
    "error": "HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /datatb/product/add/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac10e2cd00>: Failed to establish a new connection: [Errno 61] Connection refused'))"
  },
  {
    "input": {
      "name": "Product1",
      "info": "Desc1",
      "price": "20",
      "divide_by": "0"
    },
    "status_code": "exception",
    "response": "HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /datatb/product/add/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabe0062d90>: Failed to establish a new connection: [Errno 61] Connection refused'))",
    "mutation_type": "division_by_zero",
    "request_id": 9,
    "timestamp": "2025-04-24T18:38:40.711336",
    "error": "HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /datatb/product/add/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabe0062d90>: Failed to establish a new connection: [Errno 61] Connection refused'))"
  },
  {
    "input": {
      "name": "TestItem",
      "info": "Sample",
      "price": "100",
      "divide_by": "0"
    },
    "status_code": "exception",
    "response": "HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /datatb/product/add/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac10ddc4f0>: Failed to establish a new connection: [Errno 61] Connection refused'))",
    "mutation_type": "division_by_zero",
    "request_id": 15,
    "timestamp": "2025-04-24T18:38:40.730207",
    "error": "HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /datatb/product/add/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac10ddc4f0>: Failed to establish a new connection: [Errno 61] Connection refused'))"
  }
]